HorridTom/autospc

- SPCalgorithm1/src/uk/ac/ic/doc/wishnwl/tw/SPCAccumulator.java
- SPCalgorithm1/src/uk/ac/ic/doc/wishnwl/tw/SPCCalculator.java
- SPCalgorithm1/src/uk/ac/ic/doc/wishnwl/tw/SPCIO.java
I think this feature is ready to be merged into the master branch now.
> Ftr algstop

- R/plot_code.R
> Added package calls before some functions that were missed.

- README.md
Very minor change.  Fixed typo in readme.
> Fixed error in readme.

- R/algorithm.R
- R/plot_code.R
- man/plot_auto_SPC.Rd
- tests/testthat/test_integer_x.R
Plot function can now handle input x column as date, POSIXct, numeric or integer.  Output table preserves this type unless the input was POSIXct, in which case the output will be in date format.
> Bug fix non date x values

- R/functions.R
- R/plot_code.R
Handles warnings that are not to do with plotting (which will be fixed in a separate pull request). Resolves #33
> Bug fix handle warnings 33

- R/algorithm.R
- R/plot_code.R
- man/create_SPC_auto_limits_table.Rd
- man/plot_auto_SPC.Rd
> Add verbosity argument

- R/plot_code.R
- man/plot_auto_SPC.Rd
> Make caption optional

- DESCRIPTION
- R/plot_code.R
- man/create_SPC_auto_limits_table.Rd
- man/plot_auto_SPC.Rd
- renv.lock
- renv/.gitignore
- renv/activate.R
- renv/settings.json
This updates the package to work with R 4.2.3. This involved updating all dependency packages. Resolves #93
> Update to r 4.2.3

- README.md
> Update Readme to fit current package syntax.

- R/algorithm.R
- R/functions.R
- tests/testthat/test_calculation_period_length.R
- tests/testthat/test_enough_data_for_new_period.R
- tests/testthat/test_form_calculation_limits.R
This should fix #99 - would appreciate your review @ImogenConnorHelleur as I found this a complicated one to get my head around. See the issue details.
> Bugfix 99 - counter issue

- tests/testthat/test_highlights.R
- tests/testthat/test_identify_opposite_break.R
- tests/testthat/test_integer_x.R
- tests/testthat/test_linetypes.R
- tests/testthat/test_no_regrets.R
- tests/testthat/test_pass_column_names.R
- tests/testthat/test_rule2_runs.R
Hi @HorridTom could you please have a look at this?
> specific chart type defined to resolve deprecation warning message

- DESCRIPTION
- R/algorithm.R
- R/functions.R
- R/plot_code.R
- man/create_SPC_auto_limits_table.Rd
- man/plot_auto_SPC.Rd
> Feature 125 overhanging reversions

- tests/testthat/test_median_plot.R
> resolve warnings

- R/algorithm.R
- R/functions.R
- R/plot_code.R
- R/spc_functions.R
- man/create_SPC_auto_limits_table.Rd
- man/plot_auto_SPC.Rd
- tests/testthat/test_ichart_limit.R
- tests/testthat/test_mr_chart.R
@HorridTom, this implements a new argument for the user to specify the amount of mr screening (issue #114), but I'm not sure how to test it.
closes #114
> Feature mr screening 114

- DESCRIPTION
- R/plot_code.R
> Bugfix 146

- DESCRIPTION
- R/plot_code.R
- man/plot_auto_SPC.Rd
> Allow user specified date format for x-axis labels

- DESCRIPTION
- R/add_annotation_data.R
> Ensure no warnings for unlabelled points in annotation function.

- DESCRIPTION
- R/functions.R
- R/plot_code.R
- tests/testthat/test_median_plot.R
> Bugfix median na 164

- DESCRIPTION
- R/functions.R
- R/plot_code.R
- R/spc_functions.R
- man/plot_auto_SPC.Rd
- tests/testthat/test_extend_limits.R
> Feature extend limits 63

- DESCRIPTION
- R/algorithm.R
- R/functions.R
- R/log.R
- R/plot_code.R
- man/create_SPC_auto_limits_table.Rd
- man/plot_auto_SPC.Rd
- tests/testthat/test_log.R
- tests/testthat/test_too_few_points.R
> Feature log 9

- DESCRIPTION
- R/visualisation.R
> Bugfix labels msg 184
